# Generated by Django 5.2.4 on 2025-08-08 15:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la catégorie (ex: Mariage, Festival, Conférence)', max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie', verbose_name='Description')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: fas fa-music)", max_length=50, verbose_name='Icône')),
                ('couleur', models.CharField(default='#007bff', help_text='Couleur hexadécimale (ex: #007bff)', max_length=7, verbose_name='Couleur')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans les listes", verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Catégorie active et visible', verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Catégorie d'événement",
                'verbose_name_plural': "Catégories d'événement",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'événement", max_length=200, verbose_name='Titre')),
                ('description', models.TextField(help_text="Description détaillée de l'événement", verbose_name='Description')),
                ('description_courte', models.CharField(blank=True, help_text='Résumé court pour les listes', max_length=300, verbose_name='Description courte')),
                ('date_debut', models.DateTimeField(help_text="Date et heure de début de l'événement", verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(help_text="Date et heure de fin de l'événement", verbose_name='Date de fin')),
                ('lieu', models.CharField(help_text="Nom du lieu de l'événement", max_length=300, verbose_name='Lieu')),
                ('adresse', models.TextField(help_text='Adresse complète du lieu', verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Coordonnée latitude pour la carte', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Coordonnée longitude pour la carte', max_digits=11, null=True, verbose_name='Longitude')),
                ('lien_google_maps', models.URLField(blank=True, help_text='Lien vers Google Maps pour le lieu', verbose_name='Lien Google Maps')),
                ('type_acces', models.CharField(choices=[('GRATUIT', 'Gratuit'), ('PAYANT', 'Payant'), ('INVITATION', 'Sur invitation')], default='GRATUIT', help_text="Type d'accès à l'événement", max_length=20, verbose_name="Type d'accès")),
                ('prix', models.DecimalField(decimal_places=2, default=0, help_text="Prix d'entrée en FCFA", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('capacite_max', models.PositiveIntegerField(blank=True, help_text='Nombre maximum de participants (optionnel)', null=True, verbose_name='Capacité maximale')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='BROUILLON', help_text="Statut de l'événement", max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date de validation par un administrateur', null=True, verbose_name='Date de validation')),
                ('commentaire_validation', models.TextField(blank=True, help_text="Commentaire de l'administrateur", verbose_name='Commentaire de validation')),
                ('nombre_vues', models.PositiveIntegerField(default=0, help_text="Nombre de fois que l'événement a été consulté", verbose_name='Nombre de vues')),
                ('nombre_partages', models.PositiveIntegerField(default=0, help_text="Nombre de fois que l'événement a été partagé", verbose_name='Nombre de partages')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'événement", verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('billetterie_activee', models.BooleanField(default=False, help_text='Utiliser le système de billetterie intégré', verbose_name='Billetterie activée')),
                ('lien_billetterie_externe', models.URLField(blank=True, help_text="Lien vers une billetterie externe si vous n'utilisez pas le système intégré", verbose_name='Lien billetterie externe')),
                ('commission_billetterie', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission en pourcentage sur les ventes', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Commission billetterie')),
                ('createur', models.ForeignKey(help_text="Utilisateur qui a créé l'événement", on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('entite_organisatrice', models.ForeignKey(blank=True, help_text="Organisation qui organise l'événement (optionnel)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to='users.entity', verbose_name='Entité organisatrice')),
                ('validateur', models.ForeignKey(blank=True, help_text="Administrateur qui a validé l'événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
                ('categorie', models.ForeignKey(help_text="Catégorie de l'événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], help_text='Type du fichier média', max_length=10, verbose_name='Type de média')),
                ('usage', models.CharField(choices=[('galerie', 'Galerie'), ('couverture', 'Image de couverture'), ('post_cover', 'Couverture de post'), ('thumbnail', 'Miniature')], default='galerie', help_text='Usage prévu pour ce média', max_length=20, verbose_name='Usage')),
                ('fichier', models.FileField(help_text='Fichier image ou vidéo', upload_to='events/medias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov', 'webm'])], verbose_name='Fichier')),
                ('thumbnail', models.ImageField(blank=True, help_text='Miniature générée automatiquement pour les vidéos', null=True, upload_to='events/thumbnails/', verbose_name='Miniature')),
                ('titre', models.CharField(blank=True, help_text='Titre ou description du média', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du média', verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la galerie", verbose_name='Ordre')),
                ('taille_fichier', models.PositiveIntegerField(blank=True, help_text='Taille du fichier en octets', null=True, verbose_name='Taille du fichier')),
                ('largeur', models.PositiveIntegerField(blank=True, help_text='Largeur en pixels (pour les images)', null=True, verbose_name='Largeur')),
                ('hauteur', models.PositiveIntegerField(blank=True, help_text='Hauteur en pixels (pour les images)', null=True, verbose_name='Hauteur')),
                ('duree', models.DurationField(blank=True, help_text='Durée de la vidéo', null=True, verbose_name='Durée')),
                ('est_active', models.BooleanField(default=True, help_text='Média visible dans la galerie', verbose_name='Actif')),
                ('date_upload', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du média", verbose_name="Date d'upload")),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='events.event', verbose_name='Événement')),
                ('uploade_par', models.ForeignKey(help_text='Utilisateur qui a uploadé ce média', on_delete=django.db.models.deletion.CASCADE, related_name='medias_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': "Média d'événement",
                'verbose_name_plural': "Médias d'événement",
                'ordering': ['ordre', 'date_upload'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('INTERESSE', 'Intéressé'), ('PARTICIPE', 'Participe'), ('A_PARTICIPE', 'A participé'), ('ANNULE', 'Annulé')], default='INTERESSE', help_text='Type de participation', max_length=20, verbose_name='Statut')),
                ('date_participation', models.DateTimeField(auto_now_add=True, help_text="Date d'inscription à l'événement", verbose_name='Date de participation')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification du statut', verbose_name='Date de modification')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire du participant', verbose_name='Commentaire')),
                ('evenement', models.ForeignKey(help_text='Événement concerné', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event', verbose_name='Événement')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur participant', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Participation à un événement',
                'verbose_name_plural': 'Participations aux événements',
                'ordering': ['-date_participation'],
            },
        ),
        migrations.CreateModel(
            name='EventShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('LINKEDIN', 'LinkedIn'), ('EMAIL', 'Email'), ('LIEN', 'Lien direct')], help_text='Plateforme de partage', max_length=20, verbose_name='Plateforme')),
                ('date_partage', models.DateTimeField(auto_now_add=True, help_text='Date du partage', verbose_name='Date de partage')),
                ('lien_genere', models.URLField(blank=True, help_text='Lien personnalisé généré pour le partage', verbose_name='Lien généré')),
                ('nombre_clics', models.PositiveIntegerField(default=0, help_text='Nombre de clics sur le lien partagé', verbose_name='Nombre de clics')),
                ('evenement', models.ForeignKey(help_text='Événement partagé', on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='events.event', verbose_name='Événement')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur qui partage', on_delete=django.db.models.deletion.CASCADE, related_name='partages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Partage d'événement",
                'verbose_name_plural': "Partages d'événement",
                'ordering': ['-date_partage'],
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la catégorie (ex: Premium, Gold, Standard)', max_length=100, verbose_name='Nom du ticket')),
                ('description', models.TextField(blank=True, help_text='Détails sur cette catégorie de billet', verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix unitaire en FCFA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('quantite_disponible', models.PositiveIntegerField(help_text='Nombre total de billets disponibles pour ce type', verbose_name='Quantité disponible')),
                ('quantite_vendue', models.PositiveIntegerField(default=0, help_text='Nombre de billets déjà vendus', verbose_name='Quantité vendue')),
                ('date_debut_vente', models.DateTimeField(blank=True, help_text='Date à partir de laquelle ce ticket est en vente', null=True, verbose_name='Début des ventes')),
                ('date_fin_vente', models.DateTimeField(blank=True, help_text='Date de fin de disponibilité', null=True, verbose_name='Fin des ventes')),
                ('actif', models.BooleanField(default=True, help_text='Ce type de billet est-il actif ?', verbose_name='Actif')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique du billet', unique=True, verbose_name='Identifiant unique')),
                ('quantite', models.PositiveIntegerField(default=1, help_text='Nombre de billets achetés dans cette commande', verbose_name='Quantité')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé'), ('UTILISE', 'Utilisé')], default='EN_ATTENTE', help_text='Statut du billet', max_length=20, verbose_name='Statut')),
                ('code_qr', models.ImageField(blank=True, help_text='Code QR pour la validation', upload_to='tickets/qr/', verbose_name='Code QR')),
                ('date_achat', models.DateTimeField(auto_now_add=True, help_text="Date d'achat du billet", verbose_name="Date d'achat")),
                ('date_utilisation', models.DateTimeField(blank=True, help_text="Date d'utilisation du billet", null=True, verbose_name="Date d'utilisation")),
                ('reference_paiement', models.CharField(blank=True, help_text='Référence du paiement Mobile Money', max_length=100, verbose_name='Référence de paiement')),
                ('evenement', models.ForeignKey(help_text='Événement concerné', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event', verbose_name='Événement')),
                ('utilisateur', models.ForeignKey(help_text='Acheteur du billet (si acheté)', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Billet d'événement",
                'verbose_name_plural': "Billets d'événement",
                'ordering': ['prix', '-date_achat'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['statut', 'date_debut'], name='events_even_statut_b8926e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['createur', 'statut'], name='events_even_createu_71012f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['categorie', 'statut'], name='events_even_categor_0c03c7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['entite_organisatrice', 'statut'], name='events_even_entite__83f00a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmedia',
            unique_together={('evenement', 'usage', 'ordre')},
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together={('utilisateur', 'evenement')},
        ),
    ]
