# Generated by Django 5.2.4 on 2025-08-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='createur',
            field=models.ForeignKey(help_text="Utilisateur qui a créé l'événement", on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='event',
            name='validateur',
            field=models.ForeignKey(blank=True, help_text="Administrateur qui a validé l'événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validateur'),
        ),
        migrations.AddField(
            model_name='event',
            name='categorie',
            field=models.ForeignKey(help_text="Catégorie de l'événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='evenement',
            field=models.ForeignKey(help_text='Événement concerné', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur participant', on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='eventshare',
            name='evenement',
            field=models.ForeignKey(help_text='Événement partagé', on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='events.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='eventshare',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur qui partage', on_delete=django.db.models.deletion.CASCADE, related_name='partages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='evenement',
            field=models.ForeignKey(help_text='Événement concerné', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='utilisateur',
            field=models.ForeignKey(help_text='Acheteur du billet', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['statut', 'date_debut'], name='events_even_statut_b8926e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['createur', 'statut'], name='events_even_createu_71012f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['categorie', 'statut'], name='events_even_categor_0c03c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together={('utilisateur', 'evenement')},
        ),
    ]
