# Generated by Django 5.2.4 on 2025-08-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(help_text='Clé unique du paramètre', max_length=100, unique=True, verbose_name='Clé')),
                ('valeur', models.TextField(help_text='Valeur du paramètre', verbose_name='Valeur')),
                ('type_valeur', models.CharField(choices=[('STRING', 'Chaîne de caractères'), ('INTEGER', 'Nombre entier'), ('FLOAT', 'Nombre décimal'), ('BOOLEAN', 'Booléen'), ('JSON', 'JSON')], default='STRING', help_text='Type de données de la valeur', max_length=10, verbose_name='Type de valeur')),
                ('description', models.TextField(help_text='Description du paramètre', verbose_name='Description')),
                ('categorie', models.CharField(default='GENERAL', help_text='Catégorie du paramètre', max_length=50, verbose_name='Catégorie')),
                ('modifiable', models.BooleanField(default=True, help_text="Paramètre modifiable via l'interface admin", verbose_name='Modifiable')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du paramètre', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Paramètre d'application",
                'verbose_name_plural': "Paramètres d'application",
                'ordering': ['categorie', 'cle'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'expéditeur", max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(help_text="Email de l'expéditeur", max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone (optionnel)', max_length=15, verbose_name='Téléphone')),
                ('categorie', models.CharField(choices=[('SUPPORT', 'Support technique'), ('FACTURATION', 'Facturation'), ('SUGGESTION', 'Suggestion'), ('PLAINTE', 'Plainte'), ('AUTRE', 'Autre')], default='SUPPORT', help_text='Catégorie du message', max_length=20, verbose_name='Catégorie')),
                ('sujet', models.CharField(help_text='Sujet du message', max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(help_text='Contenu du message', verbose_name='Message')),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('FERME', 'Fermé')], default='NOUVEAU', help_text='Statut du message', max_length=20, verbose_name='Statut')),
                ('reponse', models.TextField(blank=True, help_text="Réponse de l'équipe", verbose_name='Réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de réception du message', verbose_name='Date de création')),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Date de première prise en charge', null=True, verbose_name='Date de traitement')),
                ('date_resolution', models.DateTimeField(blank=True, help_text='Date de résolution du message', null=True, verbose_name='Date de résolution')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'expéditeur", null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Question fréquemment posée', max_length=300, verbose_name='Question')),
                ('reponse', models.TextField(help_text='Réponse détaillée à la question', verbose_name='Réponse')),
                ('categorie', models.CharField(choices=[('GENERAL', 'Général'), ('COMPTE', 'Compte utilisateur'), ('EVENEMENTS', 'Événements'), ('PAIEMENTS', 'Paiements'), ('ABONNEMENTS', 'Abonnements'), ('TECHNIQUE', 'Technique')], default='GENERAL', help_text='Catégorie de la question', max_length=20, verbose_name='Catégorie')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la liste", verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Question visible publiquement', verbose_name='Actif')),
                ('nombre_vues', models.PositiveIntegerField(default=0, help_text='Nombre de fois que la question a été consultée', verbose_name='Nombre de vues')),
                ('utile_oui', models.PositiveIntegerField(default=0, help_text="Nombre de votes 'utile'", verbose_name='Votes utiles')),
                ('utile_non', models.PositiveIntegerField(default=0, help_text="Nombre de votes 'non utile'", verbose_name='Votes non utiles')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la FAQ', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Question fréquente',
                'verbose_name_plural': 'Questions fréquentes',
                'ordering': ['categorie', 'ordre', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du statut ou incident', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(help_text='Description détaillée', verbose_name='Description')),
                ('statut', models.CharField(choices=[('OPERATIONNEL', 'Opérationnel'), ('DEGRADED', 'Performance dégradée'), ('MAINTENANCE', 'Maintenance programmée'), ('INCIDENT', 'Incident en cours'), ('HORS_LIGNE', 'Hors ligne')], default='OPERATIONNEL', help_text='Statut actuel du système', max_length=20, verbose_name='Statut')),
                ('severite', models.CharField(choices=[('INFO', 'Information'), ('ATTENTION', 'Attention'), ('CRITIQUE', 'Critique')], default='INFO', help_text='Niveau de sévérité', max_length=10, verbose_name='Sévérité')),
                ('date_debut', models.DateTimeField(help_text="Date de début de l'incident/maintenance", verbose_name='Date de début')),
                ('date_fin_prevue', models.DateTimeField(blank=True, help_text='Date de fin prévue', null=True, verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateTimeField(blank=True, help_text='Date de fin réelle', null=True, verbose_name='Date de fin réelle')),
                ('afficher_banniere', models.BooleanField(default=True, help_text="Afficher une bannière d'information", verbose_name='Afficher bannière')),
                ('bloquer_acces', models.BooleanField(default=False, help_text="Bloquer l'accès à l'application", verbose_name='Bloquer accès')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du statut', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Statut système',
                'verbose_name_plural': 'Statuts système',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('APPROVE', 'Approbation'), ('REJECT', 'Rejet'), ('PAYMENT', 'Paiement'), ('REFUND', 'Remboursement'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('CONFIG', 'Configuration')], help_text="Type d'action effectuée", max_length=20, verbose_name='Action')),
                ('description', models.TextField(help_text="Description détaillée de l'action", verbose_name='Description')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet concerné", null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='User Agent du navigateur', verbose_name='User Agent')),
                ('donnees_avant', models.JSONField(blank=True, default=dict, help_text="État de l'objet avant modification", verbose_name='Données avant')),
                ('donnees_apres', models.JSONField(blank=True, default=dict, help_text="État de l'objet après modification", verbose_name='Données après')),
                ('date_action', models.DateTimeField(auto_now_add=True, help_text="Date et heure de l'action", verbose_name="Date de l'action")),
                ('content_type', models.ForeignKey(blank=True, help_text="Type d'objet concerné", null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-date_action'],
            },
        ),
    ]
