# Generated by Django 5.2.4 on 2025-08-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='assigne_a',
            field=models.ForeignKey(blank=True, help_text="Membre de l'équipe assigné", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text='Utilisateur expéditeur (si connecté)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='faq',
            name='createur',
            field=models.ForeignKey(help_text='Utilisateur qui a créé cette FAQ', on_delete=django.db.models.deletion.CASCADE, related_name='faqs_created', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='createur',
            field=models.ForeignKey(help_text='Utilisateur qui a créé ce statut', on_delete=django.db.models.deletion.CASCADE, related_name='system_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['utilisateur', 'date_action'], name='core_auditl_utilisa_ab4053_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'date_action'], name='core_auditl_action_57cfb7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx'),
        ),
    ]
