# Generated by Django 5.2.4 on 2025-08-02 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(help_text="Date de début de l'abonnement", verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(help_text="Date de fin de l'abonnement", verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé'), ('SUSPENDU', 'Suspendu'), ('EN_ATTENTE', 'En attente de paiement')], default='EN_ATTENTE', help_text="Statut de l'abonnement", max_length=20, verbose_name='Statut')),
                ('prix_paye', models.DecimalField(decimal_places=2, help_text='Prix effectivement payé pour cet abonnement', max_digits=10, verbose_name='Prix payé')),
                ('renouvellement_automatique', models.BooleanField(default=True, help_text="Renouveler automatiquement l'abonnement", verbose_name='Renouvellement automatique')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de souscription', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('reference_paiement', models.CharField(blank=True, help_text='Référence du paiement Mobile Money', max_length=100, verbose_name='Référence de paiement')),
                ('evenements_crees_ce_mois', models.PositiveIntegerField(default=0, help_text="Nombre d'événements créés ce mois", verbose_name='Événements créés ce mois')),
                ('derniere_reinitialisation_compteur', models.DateTimeField(auto_now_add=True, help_text='Dernière réinitialisation du compteur mensuel', verbose_name='Dernière réinitialisation compteur')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la fonctionnalité', max_length=100, verbose_name='Nom de la fonctionnalité')),
                ('description', models.TextField(help_text='Description détaillée de la fonctionnalité', verbose_name='Description')),
                ('inclus', models.BooleanField(default=True, help_text='Fonctionnalité incluse dans ce plan', verbose_name='Inclus')),
                ('limite', models.CharField(blank=True, help_text="Limite de la fonctionnalité (ex: '10 par mois', 'Illimité')", max_length=50, verbose_name='Limite')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans les listes", verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Fonctionnalité d'abonnement",
                'verbose_name_plural': "Fonctionnalités d'abonnement",
                'ordering': ['plan', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SOUSCRIPTION', 'Souscription'), ('RENOUVELLEMENT', 'Renouvellement'), ('CHANGEMENT_PLAN', 'Changement de plan'), ('ANNULATION', 'Annulation'), ('SUSPENSION', 'Suspension'), ('REACTIVATION', 'Réactivation')], help_text="Type d'action effectuée", max_length=20, verbose_name='Action')),
                ('ancien_statut', models.CharField(blank=True, help_text="Statut avant l'action", max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(help_text="Statut après l'action", max_length=20, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, help_text="Commentaire sur l'action", verbose_name='Commentaire')),
                ('date_action', models.DateTimeField(auto_now_add=True, help_text="Date de l'action", verbose_name="Date de l'action")),
            ],
            options={
                'verbose_name': "Historique d'abonnement",
                'verbose_name_plural': "Historiques d'abonnement",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom du plan d'abonnement", max_length=50, verbose_name='Nom du plan')),
                ('type_plan', models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('GOLD', 'Gold')], help_text="Type de plan d'abonnement", max_length=20, unique=True, verbose_name='Type de plan')),
                ('prix', models.DecimalField(decimal_places=2, help_text="Prix de l'abonnement en FCFA", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('duree', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], default='MENSUEL', help_text="Durée de l'abonnement", max_length=20, verbose_name='Durée')),
                ('description', models.TextField(help_text="Description du plan d'abonnement", verbose_name='Description')),
                ('max_evenements_par_mois', models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'événements par mois (null = illimité)", null=True, verbose_name='Événements max par mois')),
                ('commission_reduite', models.DecimalField(decimal_places=2, default=10.0, help_text='Taux de commission réduit en pourcentage', max_digits=5, verbose_name='Commission réduite')),
                ('support_prioritaire', models.BooleanField(default=False, help_text='Accès au support prioritaire', verbose_name='Support prioritaire')),
                ('analytics_avances', models.BooleanField(default=False, help_text='Accès aux statistiques avancées', verbose_name='Analytics avancés')),
                ('promotion_evenements', models.BooleanField(default=False, help_text='Mise en avant automatique des événements', verbose_name="Promotion d'événements")),
                ('personnalisation_profil', models.BooleanField(default=False, help_text='Options de personnalisation avancées du profil', verbose_name='Personnalisation profil')),
                ('actif', models.BooleanField(default=True, help_text='Plan disponible à la souscription', verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans les listes", verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du plan', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['ordre', 'prix'],
            },
        ),
    ]
