# Generated by Django 5.2.4 on 2025-08-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur abonné', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='subscription',
            field=models.ForeignKey(help_text='Abonnement concerné', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.subscription', verbose_name='Abonnement'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='utilisateur_action',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'action (admin)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_actions', to=settings.AUTH_USER_MODEL, verbose_name="Utilisateur de l'action"),
        ),
        migrations.AddField(
            model_name='subscriptionfeature',
            name='plan',
            field=models.ForeignKey(help_text="Plan d'abonnement", on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscriptions.subscriptionplan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(help_text="Plan d'abonnement souscrit", on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Plan'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionfeature',
            unique_together={('plan', 'nom')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['utilisateur', 'statut'], name='subscriptio_utilisa_42316a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['date_fin', 'statut'], name='subscriptio_date_fi_bff056_idx'),
        ),
    ]
