# Generated by Django 5.2.4 on 2025-08-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='analytics_avances',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='commission_reduite',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_evenements_par_mois',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='personnalisation_profil',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='promotion_evenements',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='support_prioritaire',
        ),
    ]
