# Generated by Django 5.2.4 on 2025-08-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('payments', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='organisateur',
            field=models.ForeignKey(help_text='Organisateur qui doit la commission', on_delete=django.db.models.deletion.CASCADE, related_name='commissions_dues', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur'),
        ),
        migrations.AddField(
            model_name='payment',
            name='event_ticket',
            field=models.ForeignKey(blank=True, help_text='Billet concerné (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='events.eventticket', verbose_name='Billet'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Abonnement concerné (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription', verbose_name='Abonnement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur qui effectue le paiement', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='momotransaction',
            name='payment',
            field=models.OneToOneField(help_text='Paiement associé', on_delete=django.db.models.deletion.CASCADE, related_name='momo_transaction', to='payments.payment', verbose_name='Paiement'),
        ),
        migrations.AddField(
            model_name='commission',
            name='payment',
            field=models.ForeignKey(help_text='Paiement générateur de commission', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='payments.payment', verbose_name='Paiement'),
        ),
        migrations.AddField(
            model_name='refund',
            name='demandeur',
            field=models.ForeignKey(help_text='Utilisateur qui demande le remboursement', on_delete=django.db.models.deletion.CASCADE, related_name='refunds_requested', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment_original',
            field=models.ForeignKey(help_text='Paiement à rembourser', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Paiement original'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment_remboursement',
            field=models.OneToOneField(blank=True, help_text='Paiement effectué pour le remboursement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_source', to='payments.payment', verbose_name='Paiement de remboursement'),
        ),
        migrations.AddField(
            model_name='refund',
            name='traiteur',
            field=models.ForeignKey(blank=True, help_text='Administrateur qui a traité la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to=settings.AUTH_USER_MODEL, verbose_name='Traiteur'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['utilisateur', 'statut'], name='payments_pa_utilisa_532994_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['type_paiement', 'statut'], name='payments_pa_type_pa_3f5d04_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_externe'], name='payments_pa_referen_1f68f7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date_creation'], name='payments_pa_date_cr_a87937_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['organisateur', 'statut'], name='payments_co_organis_746f07_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['type_commission', 'statut'], name='payments_co_type_co_b33bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['date_calcul'], name='payments_co_date_ca_da0d43_idx'),
        ),
    ]
