# Generated by Django 5.2.4 on 2025-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Adresse email à vérifier', max_length=254, verbose_name='Email')),
                ('code', models.CharField(help_text='Code de vérification à 6 chiffres', max_length=6, verbose_name='Code de vérification')),
                ('type_verification', models.CharField(choices=[('INSCRIPTION', 'Inscription'), ('CHANGEMENT_EMAIL', "Changement d'email"), ('REACTIVATION', 'Réactivation de compte')], default='INSCRIPTION', help_text='Type de vérification', max_length=20, verbose_name='Type de vérification')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VERIFIE', 'Vérifié'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Statut de la vérification', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du code', verbose_name='Date de création')),
                ('date_expiration', models.DateTimeField(help_text="Date d'expiration du code", verbose_name="Date d'expiration")),
                ('date_verification', models.DateTimeField(blank=True, help_text='Date de vérification réussie', null=True, verbose_name='Date de vérification')),
                ('tentatives', models.PositiveIntegerField(default=0, help_text='Nombre de tentatives de vérification', verbose_name='Tentatives')),
                ('max_tentatives', models.PositiveIntegerField(default=3, help_text='Nombre maximum de tentatives autorisées', verbose_name='Tentatives maximum')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text='Adresse IP de création', null=True, verbose_name='Adresse IP')),
            ],
            options={
                'verbose_name': "Vérification d'email",
                'verbose_name_plural': "Vérifications d'email",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_tente', models.EmailField(help_text='Email utilisé pour la tentative', max_length=254, verbose_name='Email tenté')),
                ('statut', models.CharField(choices=[('REUSSI', 'Réussi'), ('ECHEC', 'Échec'), ('BLOQUE', 'Bloqué')], help_text='Résultat de la tentative', max_length=10, verbose_name='Statut')),
                ('raison_echec', models.CharField(blank=True, help_text="Raison de l'échec de connexion", max_length=100, verbose_name="Raison de l'échec")),
                ('adresse_ip', models.GenericIPAddressField(help_text='Adresse IP de la tentative', verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='User Agent du navigateur', verbose_name='User Agent')),
                ('pays', models.CharField(blank=True, help_text="Pays d'origine de l'IP", max_length=50, verbose_name='Pays')),
                ('ville', models.CharField(blank=True, help_text="Ville d'origine de l'IP", max_length=100, verbose_name='Ville')),
                ('date_tentative', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la tentative', verbose_name='Date de tentative')),
                ('duree_session', models.DurationField(blank=True, help_text='Durée de la session (pour les connexions réussies)', null=True, verbose_name='Durée de session')),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
                'ordering': ['-date_tentative'],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token de réinitialisation', max_length=64, unique=True, verbose_name='Token')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('UTILISE', 'Utilisé'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='ACTIF', help_text='Statut du token', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du token', verbose_name='Date de création')),
                ('date_expiration', models.DateTimeField(help_text="Date d'expiration du token", verbose_name="Date d'expiration")),
                ('date_utilisation', models.DateTimeField(blank=True, help_text="Date d'utilisation du token", null=True, verbose_name="Date d'utilisation")),
                ('adresse_ip_creation', models.GenericIPAddressField(help_text='IP utilisée pour créer le token', verbose_name='IP de création')),
                ('adresse_ip_utilisation', models.GenericIPAddressField(blank=True, help_text='IP utilisée pour utiliser le token', null=True, verbose_name="IP d'utilisation")),
            ],
            options={
                'verbose_name': 'Réinitialisation de mot de passe',
                'verbose_name_plural': 'Réinitialisations de mot de passe',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook')], help_text='Fournisseur du compte social', max_length=20, verbose_name='Fournisseur')),
                ('social_id', models.CharField(help_text='Identifiant unique chez le fournisseur', max_length=100, verbose_name='ID social')),
                ('email', models.EmailField(help_text='Email associé au compte social', max_length=254, verbose_name='Email')),
                ('nom_complet', models.CharField(blank=True, help_text='Nom complet récupéré du compte social', max_length=200, verbose_name='Nom complet')),
                ('photo_url', models.URLField(blank=True, help_text='URL de la photo de profil', verbose_name='URL de la photo')),
                ('access_token', models.TextField(blank=True, help_text="Token d'accès pour l'API du fournisseur", verbose_name="Token d'accès")),
                ('refresh_token', models.TextField(blank=True, help_text='Token de rafraîchissement', verbose_name='Token de rafraîchissement')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration du token d'accès", null=True, verbose_name='Expiration du token')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de liaison du compte', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('derniere_utilisation', models.DateTimeField(blank=True, help_text='Dernière utilisation pour la connexion', null=True, verbose_name='Dernière utilisation')),
                ('actif', models.BooleanField(default=True, help_text='Compte social actif', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Compte social',
                'verbose_name_plural': 'Comptes sociaux',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=False, help_text='Authentification 2FA activée', verbose_name='Actif')),
                ('methode', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('TOTP', "Application d'authentification")], default='SMS', help_text="Méthode d'authentification 2FA", max_length=10, verbose_name='Méthode')),
                ('secret_key', models.CharField(blank=True, help_text='Clé secrète pour TOTP', max_length=32, verbose_name='Clé secrète')),
                ('codes_recuperation', models.JSONField(blank=True, default=list, help_text="Codes de récupération d'urgence", verbose_name='Codes de récupération')),
                ('derniere_utilisation', models.DateTimeField(blank=True, help_text='Dernière utilisation de 2FA', null=True, verbose_name='Dernière utilisation')),
                ('date_activation', models.DateTimeField(blank=True, help_text="Date d'activation de 2FA", null=True, verbose_name="Date d'activation")),
            ],
            options={
                'verbose_name': 'Authentification à deux facteurs',
                'verbose_name_plural': 'Authentifications à deux facteurs',
            },
        ),
    ]
