# Generated by Django 5.2.4 on 2025-08-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text='Utilisateur concerné (si existant)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur demandant la réinitialisation', on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur propriétaire du compte social', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='utilisateur',
            field=models.OneToOneField(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['adresse_ip', 'date_tentative'], name='authenticat_adresse_af731e_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['email_tente', 'date_tentative'], name='authenticat_email_t_0a6b57_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['utilisateur', 'statut'], name='authenticat_utilisa_ddbf3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'social_id')},
        ),
    ]
