# Generated by Django 5.2.4 on 2025-08-08 15:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('EVENT_CREATED', 'Événement créé'), ('EVENT_APPROVED', 'Événement approuvé'), ('EVENT_REJECTED', 'Événement rejeté'), ('EVENT_REMINDER', "Rappel d'événement"), ('EVENT_CANCELLED', 'Événement annulé'), ('NEW_FOLLOWER', 'Nouveau follower'), ('FOLLOW_EVENT', "Événement d'un suivi"), ('PAYMENT_SUCCESS', 'Paiement réussi'), ('PAYMENT_FAILED', 'Paiement échoué'), ('SUBSCRIPTION_EXPIRING', 'Abonnement expirant'), ('SUBSCRIPTION_EXPIRED', 'Abonnement expiré'), ('TICKET_PURCHASED', 'Billet acheté'), ('VERIFICATION_APPROVED', 'Vérification approuvée'), ('VERIFICATION_REJECTED', 'Vérification rejetée'), ('SYSTEM_MAINTENANCE', 'Maintenance système'), ('WELCOME', 'Bienvenue'), ('ACCOUNT_BLOCKED', 'Compte bloqué'), ('PASSWORD_CHANGE', 'Changement de mot de passe')], db_index=True, help_text='Type de notification', max_length=30, unique=True, verbose_name='Type de notification')),
                ('nom', models.CharField(help_text='Nom du template', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description du template', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Description')),
                ('titre_email', models.CharField(blank=True, help_text='Titre pour les notifications email', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Titre email')),
                ('contenu_email', models.TextField(blank=True, help_text='Contenu HTML pour les emails', validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Contenu email')),
                ('titre_push', models.CharField(blank=True, help_text='Titre pour les notifications push', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Titre push')),
                ('contenu_push', models.CharField(blank=True, help_text='Contenu pour les notifications push', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Contenu push')),
                ('contenu_sms', models.CharField(blank=True, help_text='Contenu pour les SMS (max 160 caractères)', max_length=160, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='Contenu SMS')),
                ('contenu_in_app', models.TextField(blank=True, help_text="Contenu pour les notifications dans l'application", validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Contenu in-app')),
                ('canaux_actifs', models.JSONField(blank=True, default=list, help_text='Liste des canaux activés pour ce template (ex: ["EMAIL", "PUSH"])', verbose_name='Canaux actifs')),
                ('variables_disponibles', models.JSONField(blank=True, default=list, help_text='Variables disponibles pour ce template (ex: ["user_name", "event_title"])', verbose_name='Variables disponibles')),
                ('actif', models.BooleanField(db_index=True, default=True, help_text='Template actif', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du template', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Template de notification',
                'verbose_name_plural': 'Templates de notification',
                'ordering': ['type_notification'],
                'indexes': [models.Index(fields=['type_notification'], name='notif_template_type_idx'), models.Index(fields=['actif'], name='notif_template_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('EVENT_CREATED', 'Événement créé'), ('EVENT_APPROVED', 'Événement approuvé'), ('EVENT_REJECTED', 'Événement rejeté'), ('EVENT_REMINDER', "Rappel d'événement"), ('EVENT_CANCELLED', 'Événement annulé'), ('NEW_FOLLOWER', 'Nouveau follower'), ('FOLLOW_EVENT', "Événement d'un suivi"), ('PAYMENT_SUCCESS', 'Paiement réussi'), ('PAYMENT_FAILED', 'Paiement échoué'), ('SUBSCRIPTION_EXPIRING', 'Abonnement expirant'), ('SUBSCRIPTION_EXPIRED', 'Abonnement expiré'), ('TICKET_PURCHASED', 'Billet acheté'), ('VERIFICATION_APPROVED', 'Vérification approuvée'), ('VERIFICATION_REJECTED', 'Vérification rejetée'), ('SYSTEM_MAINTENANCE', 'Maintenance système'), ('WELCOME', 'Bienvenue'), ('ACCOUNT_BLOCKED', 'Compte bloqué'), ('PASSWORD_CHANGE', 'Changement de mot de passe')], db_index=True, help_text='Type de notification', max_length=30, verbose_name='Type')),
                ('titre', models.CharField(help_text='Titre de la notification', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Titre')),
                ('message', models.TextField(help_text='Contenu de la notification', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Message')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet concerné", null=True)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], db_index=True, default='NORMALE', help_text='Priorité de la notification', max_length=10, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('LIVRE', 'Livré'), ('LU', 'Lu'), ('ECHEC', 'Échec')], db_index=True, default='EN_ATTENTE', help_text='Statut de la notification', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date de création de la notification', verbose_name='Date de création')),
                ('date_envoi', models.DateTimeField(blank=True, help_text="Date d'envoi de la notification", null=True, verbose_name="Date d'envoi")),
                ('date_lecture', models.DateTimeField(blank=True, help_text="Date de lecture par l'utilisateur", null=True, verbose_name='Date de lecture')),
                ('date_expiration', models.DateTimeField(blank=True, help_text="Date d'expiration de la notification", null=True, verbose_name="Date d'expiration")),
                ('lien_action', models.URLField(blank=True, help_text='Lien vers une action spécifique', validators=[django.core.validators.MaxLengthValidator(500)], verbose_name="Lien d'action")),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict, help_text="Données supplémentaires pour l'application", verbose_name='Données supplémentaires')),
                ('content_type', models.ForeignKey(blank=True, help_text="Type d'objet concerné", null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(help_text='Destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'statut'], name='notif_user_status'), models.Index(fields=['type_notification'], name='notif_type_idx'), models.Index(fields=['date_creation'], name='notif_creation_date_idx'), models.Index(fields=['priorite', 'statut'], name='notif_priority_status')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('EVENT_CREATED', 'Événement créé'), ('EVENT_APPROVED', 'Événement approuvé'), ('EVENT_REJECTED', 'Événement rejeté'), ('EVENT_REMINDER', "Rappel d'événement"), ('EVENT_CANCELLED', 'Événement annulé'), ('NEW_FOLLOWER', 'Nouveau follower'), ('FOLLOW_EVENT', "Événement d'un suivi"), ('PAYMENT_SUCCESS', 'Paiement réussi'), ('PAYMENT_FAILED', 'Paiement échoué'), ('SUBSCRIPTION_EXPIRING', 'Abonnement expirant'), ('SUBSCRIPTION_EXPIRED', 'Abonnement expiré'), ('TICKET_PURCHASED', 'Billet acheté'), ('VERIFICATION_APPROVED', 'Vérification approuvée'), ('VERIFICATION_REJECTED', 'Vérification rejetée'), ('SYSTEM_MAINTENANCE', 'Maintenance système'), ('WELCOME', 'Bienvenue'), ('ACCOUNT_BLOCKED', 'Compte bloqué'), ('PASSWORD_CHANGE', 'Changement de mot de passe')], db_index=True, help_text='Type de notification', max_length=30, verbose_name='Type de notification')),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Notification push'), ('SMS', 'SMS'), ('IN_APP', "Dans l'application")], db_index=True, help_text='Canal de notification', max_length=10, verbose_name='Canal')),
                ('actif', models.BooleanField(db_index=True, default=True, help_text='Recevoir ce type de notification sur ce canal', verbose_name='Actif')),
                ('frequence', models.CharField(choices=[('IMMEDIATE', 'Immédiate'), ('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('JAMAIS', 'Jamais')], default='IMMEDIATE', help_text='Fréquence de notification', max_length=20, verbose_name='Fréquence')),
                ('heure_envoi', models.TimeField(blank=True, help_text='Heure préférée pour les notifications groupées (si fréquence non immédiate)', null=True, verbose_name="Heure d'envoi")),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la préférence', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
                'ordering': ['utilisateur', 'type_notification', 'canal'],
                'indexes': [models.Index(fields=['utilisateur', 'actif'], name='notif_pref_user_active'), models.Index(fields=['type_notification', 'canal', 'actif'], name='notif_pref_type_canal_active')],
                'unique_together': {('utilisateur', 'type_notification', 'canal')},
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du lot de notifications', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Nom du lot')),
                ('filtre_utilisateurs', models.JSONField(blank=True, default=dict, help_text='Critères de filtrage des utilisateurs (ex: {"country": "BJ", "is_premium": true})', verbose_name='Filtre utilisateurs')),
                ('variables_globales', models.JSONField(blank=True, default=dict, help_text='Variables à passer au template pour toutes les notifications du lot', verbose_name='Variables globales')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], db_index=True, default='PLANIFIE', help_text="Statut de l'envoi du lot", max_length=20, verbose_name='Statut')),
                ('date_planification', models.DateTimeField(help_text="Date et heure de planification de l'envoi", verbose_name='Date de planification')),
                ('date_debut_envoi', models.DateTimeField(blank=True, help_text="Date et heure de début réel de l'envoi", null=True, verbose_name="Date de début d'envoi")),
                ('date_fin_envoi', models.DateTimeField(blank=True, help_text="Date et heure de fin réel de l'envoi", null=True, verbose_name="Date de fin d'envoi")),
                ('nombre_notifications_attendues', models.PositiveIntegerField(default=0, help_text='Nombre de notifications prévues dans ce lot', verbose_name='Notifications attendues')),
                ('nombre_notifications_envoyees', models.PositiveIntegerField(default=0, help_text='Nombre de notifications réellement envoyées', verbose_name='Notifications envoyées')),
                ('nombre_notifications_echec', models.PositiveIntegerField(default=0, help_text='Nombre de notifications ayant échoué', verbose_name='Notifications en échec')),
                ('createur', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce lot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('template', models.ForeignKey(blank=True, help_text='Template utilisé pour ce lot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_batches', to='notifications.notificationtemplate', verbose_name='Template de notification')),
            ],
            options={
                'verbose_name': 'Lot de notifications',
                'verbose_name_plural': 'Lots de notifications',
                'ordering': ['-date_planification'],
                'indexes': [models.Index(fields=['statut', 'date_planification'], name='notif_batch_status_plan_date'), models.Index(fields=['template'], name='notif_batch_template_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Token de notification push', unique=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Token')),
                ('plateforme', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], db_index=True, help_text="Plateforme de l'appareil", max_length=10, verbose_name='Plateforme')),
                ('nom_appareil', models.CharField(blank=True, help_text="Nom de l'appareil", max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name="Nom de l'appareil")),
                ('version_app', models.CharField(blank=True, help_text="Version de l'application", max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name="Version de l'application")),
                ('version_os', models.CharField(blank=True, help_text="Version du système d'exploitation", max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name="Version de l'OS")),
                ('actif', models.BooleanField(db_index=True, default=True, help_text="Token actif pour l'envoi de notifications", verbose_name='Actif')),
                ('derniere_utilisation', models.DateTimeField(auto_now=True, db_index=True, help_text='Dernière fois que le token a été utilisé', verbose_name='Dernière utilisation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date d'enregistrement du token", verbose_name='Date de création')),
                ('notifications_envoyees', models.PositiveIntegerField(default=0, help_text='Nombre de notifications envoyées à ce token', verbose_name='Notifications envoyées')),
                ('notifications_livrees', models.PositiveIntegerField(default=0, help_text='Nombre de notifications livrées avec succès', verbose_name='Notifications livrées')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur propriétaire du token', on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token de notification push',
                'verbose_name_plural': 'Tokens de notification push',
                'ordering': ['-derniere_utilisation'],
                'indexes': [models.Index(fields=['utilisateur', 'actif'], name='push_token_user_active'), models.Index(fields=['plateforme', 'actif'], name='push_token_platform_active'), models.Index(fields=['derniere_utilisation'], name='push_token_last_used')],
            },
        ),
    ]
