# Generated by Django 5.2.4 on 2025-08-02 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(help_text='Destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='createur',
            field=models.ForeignKey(help_text='Utilisateur qui a créé cette campagne', on_delete=django.db.models.deletion.CASCADE, related_name='notification_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='destinataires',
            field=models.ManyToManyField(help_text='Utilisateurs ciblés par cette campagne', related_name='notification_batches', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='template',
            field=models.ForeignKey(help_text='Template utilisé pour cette campagne', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='notifications.notificationtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='utilisateur',
            field=models.ForeignKey(help_text='Utilisateur propriétaire du token', on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'statut'], name='notificatio_utilisa_207825_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification'], name='notificatio_type_no_ba8ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['date_creation'], name='notificatio_date_cr_1b0271_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('utilisateur', 'type_notification', 'canal')},
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['utilisateur', 'actif'], name='notificatio_utilisa_2601ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['plateforme', 'actif'], name='notificatio_platefo_50f349_idx'),
        ),
    ]
