# Generated by Django 5.2.4 on 2025-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='statut',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('LIVRE', 'Livré'), ('LU', 'Lu'), ('ECHEC', 'Échec')], db_index=True, default='NOUVEAU', help_text='Statut de la notification', max_length=20, verbose_name='Statut'),
        ),
    ]
